package com.fermine.umweltlite.brain.action;

import net.minecraft.world.entity.LivingEntity;

/**
 * Represents a discrete action or state update generated by the cognitive architecture
 * that requires execution, client-side packet synchronization, or visual rendering.
 */
public interface IBrainAction {

    /**
     * @return The unique identifier string for this action type, useful for packet discrimination.
     */
    String getActionId();

    /**
     * Executes the action logic on the server or handles the local translation layer.
     *
     * @param entity The living entity instance possessing the Umwelt brain capability.
     */
    void execute(LivingEntity entity);
}